# Generated by Django 2.2.5 on 2019-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=20, verbose_name='Resposta Padrão')),
            ],
            options={
                'verbose_name': 'Resposta Padrão',
                'verbose_name_plural': 'Respostas Padrões',
                'ordering': ['texto'],
            },
        ),
    ]
