# Generated by Django 2.2.5 on 2019-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas_padroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostapadrao',
            name='texto',
            field=models.CharField(max_length=20, unique=True, verbose_name='Resposta Padrão'),
        ),
    ]
