# Generated by Django 2.2.5 on 2019-09-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_da_resposta', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('Radio Button', 'Radio Button'), ('Texto', 'Texto')], default='Radio Button', max_length=15)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.Pergunta')),
            ],
        ),
    ]
