# Generated by Django 2.2.5 on 2019-09-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resposta',
            new_name='Opcao',
        ),
        migrations.RenameField(
            model_name='opcao',
            old_name='texto_da_resposta',
            new_name='texto_da_opcao',
        ),
    ]
