# Generated by Django 2.2.5 on 2019-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
        ('opcoes', '0003_auto_20190911_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='opcao',
            name='pergunta',
            field=models.ManyToManyField(to='perguntas.Pergunta'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='texto_da_opcao',
            field=models.CharField(max_length=200, verbose_name='Texto da Opção'),
        ),
    ]
