# Generated by Django 2.2.5 on 2019-09-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
        ('opcoes', '0004_auto_20190912_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='opcao',
            name='pergunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perguntas.Pergunta'),
            preserve_default=False,
        ),
    ]
