# Generated by Django 2.2.5 on 2019-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0006_auto_20190913_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='votos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='tipo',
            field=models.CharField(choices=[('Botão', 'Botão'), ('Texto', 'Texto')], default='Botão', max_length=15),
        ),
    ]
