# Generated by Django 2.2.5 on 2019-09-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0007_auto_20190917_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='tipo',
        ),
    ]
