# Generated by Django 2.2.5 on 2019-09-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='publico_privado',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PUBLICO', max_length=10),
        ),
    ]
