# Generated by Django 2.2.5 on 2019-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20190917_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['evento', 'pergunta'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
