# Generated by Django 2.2.5 on 2019-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_auto_20190919_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['ordem'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipo',
            field=models.CharField(choices=[('Botão', 'Botão'), ('Texto', 'Texto')], default='Botão', max_length=15),
        ),
    ]
